// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopListApp.Data.Context;

#nullable disable

namespace ShopListApp.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240515174507_Deleted_wrong_entity_Products_from_Lobby")]
    partial class Deleted_wrong_entity_Products_from_Lobby
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShopListApp.Domain.Models.Lobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Lobbys");
                });

            modelBuilder.Entity("ShopListApp.Domain.Models.LobbyProduct", b =>
                {
                    b.Property<int>("LobbyId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("LobbyId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("LobbyProducts");
                });

            modelBuilder.Entity("ShopListApp.Domain.Models.LobbyUser", b =>
                {
                    b.Property<int>("LobbyId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LobbyId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("LobbyUsers");
                });

            modelBuilder.Entity("ShopListApp.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Cost")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ShopListApp.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShopListApp.Domain.Models.LobbyProduct", b =>
                {
                    b.HasOne("ShopListApp.Domain.Models.Lobby", "Lobby")
                        .WithMany("LobbyProducts")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopListApp.Domain.Models.Product", "Product")
                        .WithMany("LobbyProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopListApp.Domain.Models.LobbyUser", b =>
                {
                    b.HasOne("ShopListApp.Domain.Models.Lobby", "Lobby")
                        .WithMany("LobbyUsers")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopListApp.Domain.Models.User", "User")
                        .WithMany("LobbyUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShopListApp.Domain.Models.Lobby", b =>
                {
                    b.Navigation("LobbyProducts");

                    b.Navigation("LobbyUsers");
                });

            modelBuilder.Entity("ShopListApp.Domain.Models.Product", b =>
                {
                    b.Navigation("LobbyProducts");
                });

            modelBuilder.Entity("ShopListApp.Domain.Models.User", b =>
                {
                    b.Navigation("LobbyUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
